service: fodmap-es

frameworkVersion: "=1.28.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-2
  profile: serverless-admin

plugins:
  - serverless-finch
  - serverless-api-cloudfront

custom:
  client:
    bucketName: fodmap-es
    distributionFolder: build/
    indexDocument: index.html
    errorDocument: index.html
